### PR TITLE
Test against Ruby 2.2 and 2.3

### PR DESCRIPTION
**Pull request by hanachin**

### CODE REVIEW

**Comment by koic** [comment]
Test has failed.
Maybe it fixed by adding to `.travis.yml` like this:

```yaml
before_install: gem update bundler
```

Thanks.

**Comment by hanachin** [comment]
Thank you for your advice, I tweaked .travis.yml :smile:

**Comment by takiy33** [comment]
I think that the following change is necessary.
```diff
- 2.3
+ 2.3.0
```

**Comment by koic** [comment]
Thanks for the fix.

**Pull request merged**
